baseURL = 'http://wwww.automate-it.today/'
languageCode = 'en-us'
title = 'automate-IT'
theme = 'hugo-kiera'
googleAnalytics = 'G-1SC1SGNDCS'

[author]
    name = "Christiaan"           #Author name
    github = "vChrisR"         #Github username
    linkedin = "christiaanroeleveld"       #LinkedIn username

[params]
    tagline = "Automate everything!"
